import type { NodeModel } from "./types";

export const MOCK_NODES: NodeModel[] = [
  {
    id: 1,
    name: "Amsterdam edge",
    address: "ams-01.xrayne.net",
    port: 22,
    apiPort: 8443,
    sshUsername: "root",
    workingDirectory: "/opt/xrayne",
    note: "Primary EU entry point for production traffic.",
    certificateMode: "domain",
    apiKeyFingerprint: "dev",
    xrayVersion: "25.6.8",
    lastStatusChange: "2026-06-29T08:42:00Z",
    reconnectAttemptCount: 0,
    status: "connected",
    authType: "privateKey",
    installationMessage: "Remote node is connected.",
    createdAt: "2026-06-18T12:15:00Z",
    updatedAt: "2026-06-29T08:42:00Z",
  },
  {
    id: 2,
    name: "Singapore relay",
    address: "sgp-relay.internal",
    port: 2222,
    apiPort: 9443,
    sshUsername: "root",
    workingDirectory: "/srv/xrayne/node",
    note: "",
    certificateMode: "domain",
    apiKeyFingerprint: "dev",
    lastStatusChange: "2026-06-29T07:10:00Z",
    reconnectAttemptCount: 1,
    status: "connecting",
    authType: "password",
    message: "Waiting for the node service heartbeat.",
    installationMessage: "Connecting to remote node stream.",
    createdAt: "2026-06-22T10:30:00Z",
  },
  {
    id: 3,
    name: "Frankfurt backup",
    address: "fra-backup-01.xrayne.net",
    port: 22,
    apiPort: 8443,
    sshUsername: "root",
    workingDirectory: "/opt/xrayne",
    note: "Kept disabled until maintenance window.",
    certificateMode: "domain",
    apiKeyFingerprint: "dev",
    xrayVersion: "25.5.16",
    lastStatusChange: "2026-06-28T19:20:00Z",
    reconnectAttemptCount: 0,
    status: "disabled",
    authType: "privateKey",
    installationMessage: "Disabled by user.",
    createdAt: "2026-06-12T16:05:00Z",
    updatedAt: "2026-06-28T19:20:00Z",
  },
];
