import type { DnsQueryStrategy } from "./enums";

import type { OutboundDnsSettings } from "./outbounds";

export interface CommonRules {
  /**
   * Traffic generated by built-in DNS, except for localhost, fakedns, TCPL, DOHL, and DOQL modes, can be
   * matched with inboundTag in routing using this identifier.
   */
  tag?: string;
  /** The optimistic cache lifetime in seconds. The default value is 0 (never expires). */
  serveExpiredTTL?: number;
  /** Used to notify the server of the specified IP location during DNS queries. Cannot be a private address. */
  clientIP?: string;
  /**
   * true disables DNS caching for all DNS servers, default is false which means caching is not disabled.
   * Current option has no effect on localhost DNS and localhost DNS always use system DNS cache.
   */
  disableCache?: boolean;
  /**
   * true enables optimistic DNS caching (DNS optimistic caching). The default value is false (not
   * enabled). It only works if caching is enabled on the server (depends on DisableCache)
   */
  serveStale?: boolean;
}

/** Config for Built-in DNS server. Docs (https://xtls.github.io/config/dns.html) */
export interface DnsConfig extends CommonRules {
  /**
   * A list of static IP addresses, with values consisting of a series of "domain": "address" or
   * "domain": ["address 1","address 2"]. The address can be an IP or a domain name.
   */
  hosts?: Record<string, string | string[] | null>;
  /**
   * A list of DNS servers that supports two types: DNS addresses (in string format) and DnsServerObject
   * (https://xtls.github.io/config/dns.html#dnsserverobject).
   */
  servers?: Array<string | DnsServer>;
  /** Strategy for handling DNS rules. The default value is UseIP. */
  queryStrategy?: DnsQueryStrategy;
  /** true disables fallback DNS queries, default is false which means fallback queries are not disabled. */
  disableFallback?: boolean;
  /**
   * true disables fallback DNS queries when the matching domain list of the DNS server is hit, default
   * is false which means fallback queries are not disabled.
   */
  disableFallbackIfMatch?: boolean;
  /** if true, system-hosts appends to config-hosts at start, default is false. */
  useSystemHosts?: boolean;
}

export interface DnsServer extends CommonRules {
  /** A list of DNS servers, which can be either DNS addresses (in string form) or DnsServerObjects. */
  address?: string;
  /**
   * The port number of the DNS server, such as 53. If not specified, the default is 53. This item is not
   * applicable when using DOH, DOHL, or DOQL modes, and non-standard ports should be specified in the
   * URL.
   */
  port?: number;
  /**
   * A list of domain names. The domain names in this list will be queried using this server first. The
   * format of domain names is the same as in routing configuration
   * (https://xtls.github.io/config/routing.html#ruleobject).
   */
  domains?: string[];
  /**
   * A list of IP ranges, formatted the same as in the routing configuration
   * (https://xtls.github.io/config/routing.html#ruleobject).
   */
  expectedIPs?: string[];
  /** The reverse version, removing the IPs included in this list. The asterisk has the same effect. */
  unexpectedIPs?: string[];
  /** true — skip this server when performing DNS fallback requests. The default value is false (do not skip). */
  skipFallback?: boolean;
  /**
   * If not specified, it is inherited from the global configuration. If specified, it allows you to
   * further restrict the capabilities of this server, as well as set a default value for IP request
   * types initiated by Xray itself.
   */
  queryStrategy?: DnsQueryStrategy;
  /**
   * DNS server timeout. Default is 4000 ms. This does not affect localhost DNS (system DNS), which
   * always follows the DNS timeout behavior in Golang (cgo and pure go may differ slightly).
   */
  timeoutMs?: number;
  /** If true, the request to this DNS server will be the last attempt; fallback will not be initiated. */
  finalQuery?: boolean;
}

export type DnsSettings = OutboundDnsSettings;

/**
 * Setting up FakeDNS. Can be used in conjunction with transparent proxying to obtain real domain
 * names. Docs (https://xtls.github.io/config/fakedns.html)
 */
export interface FakeDnsConfig {
  /** FakeDNS will use the IP block specified by this option to allocate addresses. */
  ipPool?: string;
  /**
   * Specifies the maximum number of domain name-IP mappings stored by FakeDNS. When the number of
   * mappings exceeds this value, mappings will be eliminated according to the LRU rule. The default is
   * 65535.
   */
  poolSize?: number;
}

/**
 * Setting up FakeDNS. Can be used in conjunction with transparent proxying to obtain real domain
 * names. Docs (https://xtls.github.io/config/fakedns.html)
 */
export interface FaceDnsConfig extends FakeDnsConfig {}
